### ISSUE TITLE
Problem on Creating UCI Engine

### ISSUE THREAD

**Issue by MoonstoneLight** [Zerbinati/MateFinder-NN#1]
In Fritz GUI, I created this engine uci, but when I click "Add Kibitzer", MateFinder-NN doesn't exists.
Why this happens?

**Comment by Zerbinati** [comment]
You've already reported it on the forum, what's the sense in repeating it here?
However ..
https://github.com/Zerbinati/MateFinder-NN/releases/tag/091119

**Comment by MoonstoneLight** [comment]
Sorry for it. Thanks!
